name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - pandas
  - matplotlib
  - numpy
  - palmerpenguins
  - scikit-learn
  - plotly
  - seaborn
  - ipython
  - warnings